version: '3.8'

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  backend:
    container_name: backtest_api
    build: ./backtest_ui/backend
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backtest_api:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  frontend:
    container_name: backtest_ui
    build: ./backtest_ui/frontend
    volumes:
      - ./backtest_ui:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
    stdin_open: true

  telegram_pnl:
    container_name: telegram_pnl
    build: ./telegram_pnl
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT} 
      - DB_IP=${DB_IP}
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - TELEGRAM_HANDLE=${TELEGRAM_HANDLE}
      - TELEGRAM_DB_FILE=${TELEGRAM_DB_FILE}
      - TELEGRAM_CURRENT_DIR=${TELEGRAM_CURRENT_DIR}
    depends_on:
      - db
    restart: always